name: Hello World Application
# This workflow is triggered on pushes to the repository.
on: 
  push:
    branches:
      - master

jobs:
  build:
    # Job name is Greeting
    name: nodeapp
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Setup Node.js"
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: npm install
        run: npm install --production

      - name: "Login via Azure CLI"
        uses: Azure/login@v1
        with:
          creds:${{ secrets.AZUREMENODEAPP }}

      - name: "Run Azure Functions Action"
        uses: Azure/functions@v1
        id: fa
        with:
          app-name: nodeapp